### ISSUE TITLE
Question: how do I override the default cache to NOT use cookies?

### ISSUE THREAD

**Issue by webdevcody** [serverless-stack/open-next#100]
I deployed a next app using sst + open-next, but because i have google analytics on my website, a lot of things are not properly getting cached inside cloudfront due to the cookie changing every time a user loads the page.  I get a lot of cache miss.  I noticed the default cache policy is to include cookies in the cache key, but I wanted to turn that off.  

Is there a way to do this via the CDK / open-next construct?

<img width="954" alt="Screenshot 2023-04-26 at 1 40 31 AM" src="https://user-images.githubusercontent.com/123222405/234479741-a2c943c8-e5d8-4c28-a2fb-4f2a8b672e0e.png">

**Comment by bthibault** [comment]
@webdevcody what was the answer you found?
