### ISSUE TITLE
Issue deploying on AWS

### ISSUE THREAD

**Issue by pinarruiz** [serverless-stack/open-next#11]
Hi, nice project, I have some issues when deploying to lambda and using the reference archirtecture of the [README](https://github.com/serverless-stack/open-next#recommeded-infrastructure).

When I configure an origin targeting the server lambda with the middleware one in the Viewer Request I get a 503 error, so I think I am missing something or there is some part of the documentation that I have not seen, is my configuration valid?

---
#### Origin Configuration:

```txt
Origin domain: [Server Lambda URL]
Origin Name: server-lambda
Protocol: https only
```

#### Behavior Configuration:

```txt
Path Pattern: Default (*)
Origin and origin groups: server-lambda
Viewer protocol policy: Redirect HTTP to HTTPS
Allowed HTTP methods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
Cache key and origin requests:
  Cache policy: Cache Disabled
  Origin Request Policy: All viewer
Function associations:
  Viewer request: Lambda@Edge -> Middleware Lambda ARN
                              -> [x] Include Body
```

---
#### Cloudfront

The error I am are getting when I visit the CF distribution:

```txt
503 ERROR

The request could not be satisfied.

The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: [Redacted]
```

---

Thanks for any help.

**Comment by fwang** [comment]
Hi @pinarruiz, there are certain configurations need to be set on the CloudFront side, mostly around cache policy. I will document that in detail tomorrow. And then let's debug this further if those configuration changes do not help.

**Comment by pinarruiz** [comment]
> Hi @pinarruiz, there are certain configurations need to be set on the CloudFront side, mostly around cache policy. I will document that in detail tomorrow. And then let's debug this further if those configuration changes do not help.

Hi @fwang Thanks, as soon as i see the docs I will try the configuration and let you know

**Comment by pinarruiz** [comment]
Hello, i saw that you updated the docs, thanks but i still have an issue, when I visit the Cloudfront distribution, i get:
```json
{"Message":null}
```

**Comment by fwang** [comment]
Can you share a minimal repo that can reproduce the error? Or add me as a collaborator to ur repo?

Let me give it a try on my end.

**Comment by fwang** [comment]
Read your message again.. `Origin Request Policy` cannot be set to `All viewer`.

 Can you try just allowing these headers:
```
accept
x-op-middleware-request-headers
x-op-middleware-response-headers
x-nextjs-data
x-middleware-prefetch
```

Also, `/staticfile.png` should be handled by the default behaviour. And ensure the default behaviour hits the server origin and fails over to s3 origin.

**Comment by pinarruiz** [comment]
Hi, so the config had change according to what was updated on the readme, but I am still not getting the fallback side of it do i have to implement it on my own? As far as I know there is no fallback option.
