### ISSUE TITLE
Add support for Server Actions

### ISSUE THREAD

**Issue by francoisdtm** [serverless-stack/open-next#116]
Hi everyone! I would love to use [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions) in my projects.

At the moment, CloudFront returns a 403 error when a server action call is performed.

**Comment by jayair** [comment]
Join us on Discord? #open-next

**Comment by fwang** [comment]
@francoisdtm I updated the README to reflect the new suggested AWS infrastructure design to support server actions.

If you happen to use SST to deploy, update to v2.16.3 and it should just work.

If u have issues after upgrading to v2.16.3, ping me in #open-next on Discord

**Comment by smith558** [comment]
> @francoisdtm I updated the README to reflect the new suggested AWS infrastructure design to support server actions.
> 
> If you happen to use SST to deploy, update to v2.16.3 and it should just work.
> 
> If u have issues after upgrading to v2.16.3, ping me in #open-next on Discord

Can you please point me to where this is mentioned? Can't seem to find it.

**Comment by khuezy** [comment]
@francoisdtm @smith558 @jayair @fwang @anasmohammed361 
You can see the server actions here on the live e2e app:
Just click the "Fire Server Actions" and it will send the request.

[OpenNext Server Actions Demo](https://d1ub7xgpknvo1z.cloudfront.net/server-actions)

**Comment by jayair** [comment]
lmao 
<img width="740" alt="Screenshot 2024-09-06 at 5 13 47 PM" src="https://github.com/user-attachments/assets/e0358042-e54d-4784-9764-5a405a8d7386">
