### ISSUE TITLE
MessageDeduplicationId is invalid

### ISSUE THREAD

**Issue by mathisobadia** [serverless-stack/open-next#138]
There is an issue with the revalidate function when the path of the page is really long, here is the log:
```
error: InvalidParameterValue: Value /_next/data/L_8eQ3HtfyWgwhPcHzY3s/news/former-texas-congressman-will-hurd-a-trump-critic-announces-2024-republican-presidential-campaign-710f6f0d.json-"utf9noheh4ujg" for parameter MessageDeduplicationId is invalid. 
Reason: MessageDeduplicationId can only include alphanumeric and punctuation characters. 1 to 128 in length.
```

As the message indicates the issue is that the duplication id is longer than 128 characters.

here is the relevant code:
https://github.com/serverless-stack/open-next/blob/45d67314748c0875ad9972203272a3e1328af808/packages/open-next/src/adapters/server-adapter.ts#LL255C1-L286C1

 I think we might need to hash it for it to work because truncating it will produce some errors if pages share the same first part of the url

I can open a PR with the required changes, if anyone has a better idea let me know

**Comment by fwang** [comment]
Released in v2.0.1
