### ISSUE TITLE
Error while building through : ```npx open-next build```

### ISSUE THREAD

**Issue by ibraelillo** [serverless-stack/open-next#3]
Bundling server function...
file:///home/ibra/accor/astore/node_modules/.pnpm/open-next@0.0.1/node_modules/open-next/dist/build.js:41
            path.resolve(__dirname, "../assets/server-handler.js")
                         ^

ReferenceError: __dirname is not defined
    at createServerBundle (file:///home/ibra/accor/astore/node_modules/.pnpm/open-next@0.0.1/node_modules/open-next/dist/build.js:41:26)
    at build (file:///home/ibra/accor/astore/node_modules/.pnpm/open-next@0.0.1/node_modules/open-next/dist/build.js:25:5)

**Comment by fwang** [comment]
Hey @ibraelillo can you give v0.1.0 a try and see if it's fixed?

^ make sure to run `open-next` with the `latest` npm version. ie. `npx open-next@latest build`

**Comment by DiemasMichiels** [comment]
This one seemed to be fixed.
Version `0.0.1` didn't have this line: `const __dirname = url.fileURLToPath(new URL(".", import.meta.url));` in the `build.ts` file.

**Comment by fwang** [comment]
Closing for now. Feel free to re-open if not fixed.
