### ISSUE TITLE
Cannot find package esbuild @vercel/next @vercel/build-utils serverless-http

### ISSUE THREAD

**Issue by DiemasMichiels** [serverless-stack/open-next#4]
When running the command: `npx open-next build`
The following packages are missing:

- `esbuild`
- `@vercel/next`
- `@vercel/build-utils`
- `serverless-http`

The error for a missing package:
```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from /Users/me/.npm/_npx/023205fa7f8910ff/node_modules/open-next/dist/build.js
 {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Installing them resolved this issue, but I suspect it needs to work without installing any other dependencies locally.

**Comment by fwang** [comment]
Thanks @DiemasMichiels. Fixed in v0.1.0.

Make sure you run `open-next` with the `latest` npm version. ie. `npx open-next@latest build`
