### ISSUE TITLE
Middleware rewrite does not work

### ISSUE THREAD

**Issue by mathisobadia** [serverless-stack/open-next#45]
This issue was mentioned on discord and there is an open PR about it but I thought it would be good to open an issue to track it.
Basically middleware rewrite does not work when the nextjs site is deployed with sst. 

To confirm this I forked open-next, added sst drop in mode to the example nextjs project and deployed it. Here is the deployed address for rewrite https://dooy830n0j9e.cloudfront.net/middleware-rewrite . The page does not work when accessed directly and is missing the check mark when you navigate to it. You can compare it to the deployed vercel one and see the green check mark https://open-next.vercel.app/middleware-rewrite

Here is the diff of me adding sst to the example https://github.com/serverless-stack/open-next/compare/main...mathisobadia:open-next:main. On a side note, I can open a PR to add it to the open-next example. It would be a good example of how to deploy with sst.

**Comment by mathisobadia** [comment]
So I just did some digging into next code and the reason this does not work is because of the minimal mode
https://github.com/vercel/next.js/blob/e91de8e0ddfd5b4a996c0e5df6549fe3981e1f6d/packages/next/src/server/next-server.ts#L1862

**Comment by fwang** [comment]
Hey @mathisobadia, we re-architectured how middleware is deployed in v0.8.0. Details are shared here — https://github.com/serverless-stack/open-next#will-my-nextjs-app-behave-the-same-as-it-does-on-vercel

It's a lot more robust now. Give v0.9.0 a try!
