### ISSUE TITLE
CloudFront error: Lambda@Edge does not support functions with an architecture of arm64

### ISSUE THREAD

**Issue by juliocorzo** [serverless-stack/open-next#47]
I was under the impression that the image optimization function was meant to be arm64?

![](https://i.imgur.com/omGivM5.png)

**Comment by juliocorzo** [comment]
Also might want to write down the 128 MB memory and 5 sec timeout on viewer request functions like middleware

**Comment by juliocorzo** [comment]
Thank you, do you mean that the function url should be added as that origin for that cache behavior (vs adding the function itself as the origin request and response)

**Comment by fwang** [comment]
Yup that's correct!
Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps
