### ISSUE TITLE
Invalid path for export for server function on monorepo package in windows

### ISSUE THREAD

**Issue by rwlanup** [serverless-stack/open-next#60]
In monorepo environment, `open-next` exports the real handler from dummy `index.mjs`. The path for the real handler is wrong in windows.

For following configuration, open-next fails to output correct path in windows:
Monorepo root: `D:\my-app`
App path: `D:\my-app\packages\frontend`

This outputs the `index.mjs` with following content:
```
export * from "./packages\frontend/index.mjs";
```
It should be
```
export * from "./packages/frontend/index.mjs";
```

**Comment by fwang** [comment]
Fixed in v1.0.0
