### ISSUE TITLE
[feature/idea]: lambda response streaming

### ISSUE THREAD

**Issue by thiskevinwang** [serverless-stack/open-next#76]
AWS just announced Lambda response streaming: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-response-payload-streaming/

Curious if there is potential to leverage streams here.

Thanks again for this awesome project!

**Comment by thiskevinwang** [comment]
Sorry, I got this project mixed up with https://github.com/jetbridge/cdk-nextjs. 🤦 Will close this for now.

**Comment by khuezy** [comment]
cdk-nextjs now uses open-next.
`0.0.0-streaming.8` is the latest streaming RC
