### ISSUE TITLE
Copy / pasting code without attribution, breaking license!

### ISSUE THREAD

**Issue by festivaljogger** [serverless-stack/open-next#80]
@dougmoscrop's code is being copy/pasted here without attribution:
- https://github.com/serverless-stack/open-next/blob/main/packages/open-next/src/adapters/request.ts
- https://github.com/serverless-stack/open-next/blob/main/packages/open-next/src/adapters/response.ts

Original source:
- https://github.com/dougmoscrop/serverless-http/blob/master/lib/request.js
- https://github.com/dougmoscrop/serverless-http/blob/master/lib/response.js

**Comment by fwang** [comment]
Thanks for catching it! My bad to omit that. I'd have pulled my hair out constructing the request/response without the help from `serverless-http` project.

@festivaljogger does the attribution look good here — https://github.com/serverless-stack/open-next/commit/3db0c1932e3af17f7f794b89a43e20c0beed8f6d

Let me know if anything I missed.

**Comment by fwang** [comment]
Added reference to `serverless-http` in the new [Acknowledgements](https://github.com/serverless-stack/open-next#acknowledgements) section 🙏
